# Generated by Django 4.2.5 on 2023-10-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_pedidosexames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosexames',
            old_name='data',
            new_name='data_pedido',
        ),
    ]
